#!/bin/sh

# quit if we're called for the loopback
if [ "$IFACE" != wlan0 ]; then
	exit 0
fi

do_start () {
    #systemctl restart gmediarender
    killall gmediarender
    /etc/init.d/gmediarender restart
}

do_stop () {
    true
}

case "$MODE" in 
	start)
		do_start
		case "$PHASE" in
			pre-up)
				;;
			post-up)
				;;
		esac
		;;

	stop)
		do_stop
		case "$PHASE" in
			pre-down)
				;;
			post-down)
				;;
			*)
				exit 1
				;;
		esac
		;;
	
	*)
		exit 1
		;;
esac

exit 0
